changed pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -59,7 +59,16 @@ deploy-fastapi-apps:
 #    - export GAME_RECOMMENDER_API_URL=$(az webapp show --name game-recommender-api-app --resource-group BanditGames --query 'defaultHostName' -o tsv)
 #    - echo "Game recommender URL $GAME_RECOMMENDER_API_URL"
     - echo "Deploying chatbot api..."
-    - az containerapp wait --name chatbot-api-ca --resource-group BanditGames --created
+    - STATE=$(az containerapp show --name chatbot-api-ca --resource-group BanditGames --query "properties.provisioningState" -o tsv || echo "NotFound")
+    - if [ "$STATE" = "InProgress" ]; then
+      echo "Chatbot API is currently being provisioned. Waiting...";
+      sleep 30;
+      exit 1;
+      elif [ "$STATE" = "NotFound" ]; then
+      echo "Chatbot API not found. Proceeding with creation...";
+      else
+      echo "Chatbot API is ready for deployment.";
+      fi
     - az containerapp up --name chatbot-api-ca 
       --resource-group BanditGames 
       --location westeurope 
